version: '3.6'
services:
  ch-zookeeper:
    image: zookeeper:3.5
    container_name: ch-zookeeper
    hostname: ch-zookeeper
    volumes:
      - ch_zk_data:/var/lib/zookeeper/data
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./config/config-01.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./dataImport:/data/dataImport
      - ch_01_data:/var/lib/clickhouse/
    depends_on:
      - ch-zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ./config/config-02.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./dataImport:/data/dataImport
      - ch_02_data:/var/lib/clickhouse/
    depends_on:
      - ch-zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ./config/config-03.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./dataImport:/data/dataImport
      - ch_03_data:/var/lib/clickhouse/
    depends_on:
      - ch-zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:22.3.2.2
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ./config/config-04.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./dataImport:/data/dataImport
      - ch_04_data:/var/lib/clickhouse/
    depends_on:
      - ch-zookeeper
networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24

volumes:
  ch_01_data:
  ch_02_data:
  ch_03_data:
  ch_04_data:
  ch_zk_data:
