version: '3.6'
services:
  server:
    image: clickhouse/clickhouse-server:22.3.2.2
    networks:
      - clickhouse_default
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./ontime.tar:/data/ontime.tar
      - ./statOpt:/data/statOpt

  client:
    image: clickhouse/clickhouse-client:latest
    depends_on:
      - server
    links:
      - server
    entrypoint:
        - /bin/sleep
    command:
        - infinity
    networks:
      - clickhouse_default

networks:
  clickhouse_default:
    driver: bridge

volumes:
  portainer_data:
